Import Libraries

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

Create dataframe

In [ ]:
df = pd.read_csv('/content/fact_saless.csv')

In [ ]:
df.head()

,DateKey,ProductKey,BranchKey,Sales_Quantity,Unit_Price,Unit_Cost,Revenue,Total_Cost,Net_Profit,Profit_Margin,Expired_Quantity,Damaged_Quantity,Waste_Quantity,Waste_Rate
0,20210101,1,1,24,89.82,58.64,2155.68,1407.36,748.32,0.347139,0,0,0,0.000000
1,20210101,2,1,135,100.94,67.55,13626.90,9119.25,4305.00,0.315919,2,1,3,0.022222
2,20210101,3,1,552,35.43,20.77,19557.36,11465.04,8030.01,0.410588,0,3,3,0.005435
3,20210101,4,1,38,29.24,21.71,1111.12,824.98,286.14,0.257524,0,0,0,0.000000
4,20210101,5,1,20,87.09,57.26,1741.80,1145.20,596.60,0.342519,0,0,0,0.000000

In [ ]:
def risk_level(row):
  score = 0
  if row["Waste_Rate"] >= 0.10:
    score += 2
  if row["Expired_Quantity"] >= 3:
    score += 2
  if row["Damaged_Quantity"] >= 2:
    score += 1
  if row["Profit_Margin"] < 0.20:
    score += 1

  if score >= 4:
    return "High Risk"
  elif score >= 2:
    return "Medium Risk"
  else:
    return "Low Risk"
df["Risk_Level"] = df.apply(risk_level, axis=1)

In [ ]:
df["Risk_Level"].value_counts()

Risk_Level
Low Risk       755445
Medium Risk     33663
High Risk       32142
Name: count, dtype: int64

In [ ]:
features = ["ProductKey", "BranchKey", "Sales_Quantity", "Revenue", "Total_Cost"]

In [ ]:
X = df[features]
Y = df["Risk_Level"]

In [ ]:
encoder = LabelEncoder()
Y = encoder.fit_transform(Y)

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [ ]:
model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(X_train, Y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [ ]:
predictions = model.predict(X_test)

In [ ]:
acc = accuracy_score(Y_test, predictions)
print(f"Accuracy: {acc}")

Accuracy: 0.9849741248097412

In [ ]:
print(classification_report(Y_test, predictions, target_names=encoder.classes_))

              precision    recall  f1-score   support

   High Risk       0.85      0.85      0.85      6388
    Low Risk       1.00      1.00      1.00    151196
 Medium Risk       0.84      0.84      0.84      6666

    accuracy                           0.98    164250
   macro avg       0.90      0.90      0.90    164250
weighted avg       0.99      0.98      0.98    164250

In [ ]:
conmat = confusion_matrix(Y_test, predictions)
print(conmat)

[[  5459    182    747]
 [   166 150693    337]
 [   767    269   5630]]

In [ ]:
df.head(50)

,DateKey,ProductKey,BranchKey,Sales_Quantity,Unit_Price,Unit_Cost,Revenue,Total_Cost,Net_Profit,Profit_Margin,Expired_Quantity,Damaged_Quantity,Waste_Quantity,Waste_Rate,Risk_Level
0,20210101,1,1,24,89.82,58.64,2155.68,1407.36,748.32,0.347139,0,0,0,0.000000,Low Risk
1,20210101,2,1,135,100.94,67.55,13626.90,9119.25,4305.00,0.315919,2,1,3,0.022222,Low Risk
2,20210101,3,1,552,35.43,20.77,19557.36,11465.04,8030.01,0.410588,0,3,3,0.005435,Low Risk
3,20210101,4,1,38,29.24,21.71,1111.12,824.98,286.14,0.257524,0,0,0,0.000000,Low Risk
4,20210101,5,1,20,87.09,57.26,1741.80,1145.20,596.60,0.342519,0,0,0,0.000000,Low Risk
5,20210101,6,1,11,164.52,113.49,1809.72,1248.39,561.33,0.310175,0,0,0,0.000000,Low Risk
6,20210101,7,1,27,67.99,44.84,1835.73,1210.68,400.85,0.218360,5,0,5,0.185185,High Risk
7,20210101,8,1,22,102.22,70.71,2248.84,1555.62,693.22,0.308257,0,0,0,0.000000,Low Risk
8,20210101,9,1,21,130.89,87.52,2748.69,1837.92,910.77,0.331347,0,0,0,0.000000,Low Risk
9,20210101,10,1,14,53.69,40.14,751.66,561.96,189.70,0.252375,0,0,0,0.000000,Low Risk
10,20210101,11,1,19,114.71,81.03,2179.49,1539.57,315.80,0.144896,4,0,4,0.210526,High Risk
11,20210101,12,1,24,135.30,141.74,3247.20,3401.76,-579.78,-0.178548,3,0,3,0.125000,High Risk
12,20210101,13,1,114,29.56,17.29,3369.84,1971.06,1398.78,0.415088,0,0,0,0.000000,Low Risk
13,20210101,14,1,10,60.81,41.24,608.10,412.40,195.70,0.321822,0,0,0,0.000000,Low Risk
14,20210101,15,1,18,121.12,86.45,2180.16,1556.10,624.06,0.286245,0,0,0,0.000000,Low Risk
15,20210101,16,1,18,64.69,44.20,1164.42,795.60,368.82,0.316741,0,0,0,0.000000,Low Risk
16,20210101,17,1,19,92.39,67.04,1755.41,1273.76,481.65,0.274380,0,0,0,0.000000,Low Risk
17,20210101,18,1,20,20.56,14.61,411.20,292.20,119.00,0.289397,0,0,0,0.000000,Low Risk
18,20210101,19,1,20,146.91,101.89,2938.20,2037.80,900.40,0.306446,0,0,0,0.000000,Low Risk
19,20210101,20,1,19,134.95,99.34,2564.05,1887.46,676.59,0.263876,0,0,0,0.000000,Low Risk
20,20210101,21,1,16,120.28,87.83,1924.48,1405.28,519.20,0.269787,0,0,0,0.000000,Low Risk
21,20210101,22,1,12,65.64,45.80,787.68,549.60,238.08,0.302255,0,0,0,0.000000,Low Risk
22,20210101,23,1,19,168.10,111.15,3193.90,2111.85,1082.05,0.338786,0,0,0,0.000000,Low Risk
23,20210101,24,1,14,16.17,12.03,226.38,168.42,57.96,0.256030,0,0,0,0.000000,Low Risk
24,20210101,25,1,13,90.82,67.11,1180.66,872.43,308.23,0.261066,0,0,0,0.000000,Low Risk
25,20210101,26,1,20,112.88,75.40,2257.60,1508.00,749.60,0.332034,0,0,0,0.000000,Low Risk
26,20210101,27,1,3,126.56,85.74,379.68,257.22,122.46,0.322535,0,0,0,0.000000,Low Risk
27,20210101,28,1,19,12.85,8.41,244.15,159.79,84.36,0.345525,0,0,0,0.000000,Low Risk
28,20210101,29,1,3,73.43,48.35,220.29,145.05,75.24,0.341550,0,0,0,0.000000,Low Risk
29,20210101,30,1,10,114.29,78.08,1142.90,780.80,362.10,0.316826,0,0,0,0.000000,Low Risk
30,20210101,31,1,13,154.07,107.41,2002.91,1396.33,284.35,0.141968,3,0,3,0.230769,High Risk
31,20210101,32,1,8,153.62,111.17,1228.96,889.36,339.60,0.276331,0,0,0,0.000000,Low Risk
32,20210101,33,1,28,144.70,77.31,4051.60,2164.68,1886.92,0.465722,0,0,0,0.000000,Low Risk
33,20210101,34,1,964,34.19,18.88,32959.16,18200.32,14588.92,0.442636,0,9,9,0.009336,Low Risk
34,20210101,35,1,23,43.13,31.28,991.99,719.44,272.55,0.274751,0,0,0,0.000000,Low Risk
35,20210101,36,1,54,84.41,55.14,4558.14,2977.56,1525.44,0.334663,1,0,1,0.018519,Low Risk
36,20210101,37,1,15,109.25,80.03,1638.75,1200.45,438.30,0.267460,0,0,0,0.000000,Low Risk
37,20210101,38,1,18,109.74,72.60,1975.32,1306.80,668.52,0.338436,0,0,0,0.000000,Low Risk
38,20210101,39,1,12,163.58,112.52,1962.96,1350.24,612.72,0.312141,0,0,0,0.000000,Low Risk
39,20210101,40,1,46,167.32,181.44,7696.72,8346.24,-649.52,-0.084389,0,0,0,0.000000,Low Risk
40,20210101,41,1,15,52.23,36.27,783.45,544.05,239.40,0.305572,0,0,0,0.000000,Low Risk
41,20210101,42,1,192,25.20,13.23,4838.40,2540.16,2285.01,0.472266,0,1,1,0.005208,Low Risk
42,20210101,43,1,152,123.63,63.10,18791.76,9591.20,9137.46,0.486248,0,1,1,0.006579,Low Risk
43,20210101,44,1,14,139.23,101.30,1949.22,1418.20,531.02,0.272427,0,0,0,0.000000,Low Risk
44,20210101,45,1,18,109.93,73.17,1978.74,1317.06,661.68,0.334395,0,0,0,0.000000,Low Risk
45,20210101,46,1,14,24.52,16.67,343.28,233.38,109.90,0.320147,0,0,0,0.000000,Low Risk
46,20210101,47,1,19,85.98,58.33,1633.62,1108.27,525.35,0.321586,0,0,0,0.000000,Low Risk
47,20210101,48,1,15,91.82,66.41,1377.30,996.15,381.15,0.276737,0,0,0,0.000000,Low Risk
48,20210101,49,1,10,88.59,61.83,885.90,618.30,267.60,0.302066,0,0,0,0.000000,Low Risk
49,20210101,50,1,28,49.13,55.06,1375.64,1541.68,-166.04,-0.120700,0,0,0,0.000000,Low Risk

In [ ]:
import ipywidgets as widgets
from IPython.display import display

product = widgets.IntText(description='Product')
branch = widgets.IntText(description='Branch')
sales = widgets.FloatText(description='Sales')
revenue = widgets.FloatText(description='Revenue')
cost = widgets.FloatText(description='Cost')

display(product, branch, sales, revenue, cost)
button = widgets.Button(description="Predict")

output = widgets.Output()

def predict(b):
    with output:
        output.clear_output()

        user = pd.DataFrame({
            "ProductKey":[product.value],
            "BranchKey":[branch.value],
            "Sales_Quantity":[sales.value],
            "Revenue":[revenue.value],
            "Total_Cost":[cost.value]
        })

        pred = model.predict(user)

        risk = encoder.inverse_transform(pred)

        print("Predicted Risk Level:", risk[0])

button.on_click(predict)

display(button, output)

IntText(value=0, description='Product')

IntText(value=0, description='Branch')

FloatText(value=0.0, description='Sales')

FloatText(value=0.0, description='Revenue')

FloatText(value=0.0, description='Cost')

Button(description='Predict', style=ButtonStyle())

Output()